### ISSUE TITLE
Download source does not include my keymap file

### ISSUE THREAD

**Issue by jeep** [qmk/qmk_configurator#1006]
### Describe the Bug

When I create a keymap, hit compile, then select "Full Source" to download the full source, I expected the download to contain my custom keymap. Since I select Ergodox_ez and named my keymap "jeep" I expected to find it in qmk_firmware/keyboards/ergodox_ez/keymaps/jeep or possibly .../default. But I did not find it in either place. When I hit "firmware" it did tell me that my changes might not be saved, but it did download a correct .hex file. So perhaps it isn't saving the file? (I wanted to do a minor tweak to control the lights to indicate the layer.)

Is there someplace else I should be looking for the file?

**Comment by fauxpark** [comment]
The keymap JSON file should be in the root directory. The keymap.c is generated by the backend when you hit compile and won't be present in the full source .zip. You can use `qmk json2c` locally to convert the JSON file to a keymap.c.
