### ISSUE TITLE
Shifted symbols do not work with LT<n>

### ISSUE THREAD

**Issue by jeep** [qmk/qmk_configurator#1007]
### Describe the Bug

When I used LT(1,%) I expected it to apply layer 1 when held and produce a % when tapped, but instead it prints 5 when I tap the key and correctly turns on Layer 1 when I hold.  When I apply only the shifted key, it correctly prints the %.

I am using Ergodox EZ with Windows 10. I also tried with ~ and the same result. It produces a tick instead of a tilde.

### Additional Context?

![Screenshot 2021-10-21 163859](https://user-images.githubusercontent.com/89500/138371254-4f36ee03-50d3-473a-bd31-9417200fc642.png)
The left key works as expected and produces a %.
The right key does not work as expected. Instead of a % it produces a 5 (the unshifted version)

**Comment by yanfali** [comment]
This may be a limitation of split, it might not be sending the mod shift
over the wire. Can you connect the right half to USB and retest? In which
case this is a qmk issue and not configurator.

**Comment by yanfali** [comment]
Ah. So shifted values don't work with LT as I understand it. This is
equivalent to holding 2 keys.

**Comment by yanfali** [comment]
I think you can write custom code, which means you can't use configurator for this. You could try the EZ configurator Onyx, it may have a way to support this.
