### ISSUE TITLE
[Bug] Compiler error for Lets Split V2

### ISSUE THREAD

**Issue by mavaron81** [qmk/qmk_configurator#1011]
### Describe the Bug

Took some testing to figure out what was wrong, but new Lets Split V2 hex compiles from a JSON made in May do not work - specifically, the right side of the Let's Split will be dead. However, a hex compilation that was made in May of that same JSON works.

This essentially leaves me unable to update my Let's Split until the error is fixed. 

The files I used are attached:

[Recompile.zip](https://github.com/qmk/qmk_configurator/files/7422563/Recompile.zip)

**Comment by ferronand** [comment]
I have the same issue with my dactyl manuform 5x6.  Flashing a hex file built in Jan 2021 works fine, but compiling now from the same json file builds a hex file that when flashed, the right side of the keyboard is dead.

**Comment by yanfali** [comment]
> I have the same issue with my dactyl manuform 5x6. Flashing a hex file built in Jan 2021 works fine, but compiling now from the same json file builds a hex file that when flashed, the right side of the keyboard is dead.

Did you flash both sides?

**Comment by ferronand** [comment]
> 

I don't normally need to flash both sides.  I have flashed different layouts many times in the past using the flash button I wired up when I built it.  I can still flash old hex files files fine.  Is there some recent change in the firmware files that would make it so I now need to take apart the keyboard and flash both sides?

**Comment by ferronand** [comment]
> > 
> 
> I don't normally need to flash both sides. I have flashed different layouts many times in the past using the flash button I wired up when I built it. I can still flash old hex files files fine. Is there some recent change in the firmware files that would make it so I now need to take apart the keyboard and flash both sides?

I took it apart and flashed the other side, then flashed again through the master side.  It works now.  Thank you
