### ISSUE TITLE
[Bug] Missing CONTROL+GUI mod key combination

### ISSUE THREAD

**Issue by jin-ahn** [qmk/qmk_configurator#1024]
### Describe the Bug

In the qmk configurator, there is no option to do a `LCG` or `RCG` for CONTROL+GUI mod combination. There is a `OSM CG` for a 1 keypress, but there needs to be one where it is the mod key combination

**Comment by yanfali** [comment]
As a work around you can use ANY to do this. It's difficult to anticipate every possible combination in the UI so less common ones aren't necessarily populated.
