### ISSUE TITLE
[Feature Request] Ctrl+Gui modifier does not exist.

### ISSUE THREAD

**Issue by ZaxonXP** [qmk/qmk_configurator#1040]
When looking on the [web qmk configurator](https://github.com/qmk/qmk_configurator) I could not find the Ctrl+Gui modifier on the quantum tab. This combination is needed to use virtual desktops under Windows (Ctrl+Gui+Left/Right) is used to move to next/previous virtual desktop. Could you please add this missing key modifiers?

Kind regards,
Piotr

**Comment by zvecr** [comment]
In the short term, you can use something like `C(G(KC_LEFT))` with the `Any` key.

**Comment by ZaxonXP** [comment]
OK. This was not obvious to me how to use the Any key. Thanks.
