### ISSUE TITLE
[Bug] escape key isn't working after flashing dz60rgb

### ISSUE THREAD

**Issue by enpierre** [qmk/qmk_configurator#1045]
### Describe the Bug

So, I recently got the dz60rgb pcb and when I flashed it the escape key suddenly stopped working I tried the ansi layout and it worked, and I use the escape key to reset my keyboard and it works so its probably something with the layout I'm using. Pls help.

**Comment by yanfali** [comment]
If you're talking about Bootmagic lite, then you unplug the keyboard, then plug it in while holding the ESC key and it will put the firmware into programming mode. It's enabled for your keyboard, assuming it's a v2_1.
