### ISSUE TITLE
[Bug] Keyboard Hillside is not loading its default keymap

### ISSUE THREAD

**Issue by mmccoyd** [qmk/qmk_configurator#1046]
### Describe the Bug

Hillside has a default keymap in hardwired/hillside/keymaps/default/keymap.json, yet it is not loaded when the keyboard is selected nor when the default button is pressed.

It does load successfully if done so with the upload JSON button.

### Additional Context?

Hillside was merged into QMK with https://github.com/qmk/qmk_firmware/pull/15399#ref-commit-ede43cd on January 8.

**Comment by yanfali** [comment]
Doesn't work that way I'm afraid. Keymaps aren't loaded from the repo for technical reasons. @noroadsleft

**Comment by mmccoyd** [comment]
Ok. I did not realize. The keyboard and its layout got from qmk to the configurator. 

How to I trigger the layout to get there as well?

**Comment by yanfali** [comment]
Someone needs to add a default keymap for configurator. I'm sure noroads has it in hand.

**Comment by noroadsleft** [comment]
Solved by #1074.
