### ISSUE TITLE
[Bug] Keebio BFO-9000 does not occasionally work

### ISSUE THREAD

**Issue by Risord** [qmk/qmk_configurator#1067]
### Describe the Bug

This issue seems somewhat weird but couple of days ago I could not edit keebio bfo-9000 layout since 
GET request for https://keyboards.qmk.fm/v1/keyboards/keebio/bfo9000/info.json returns 504 Gateway Timeout.

After short period of time it started to work but issue is now back on. I have not found any other layout with same issue.

**Comment by Risord** [comment]
(And now it's working again...)

**Comment by fauxpark** [comment]
@Risord is this still an issue?

**Comment by Risord** [comment]
@fauxpark well I haven't used that configurator for BFO for long time but it works now so let's close this. I will report if that reappears.
