### ISSUE TITLE
Can't download hex file, instead it's a blank text file

### ISSUE THREAD

**Issue by jibreil** [qmk/qmk_configurator#107]
I'm trying to flash my GH60 and have done so multiple times in the past few days by compiling and downloading the hex from qmk_configurator.

Today when I press `Download .hex`, it tries to download `download.txt` which is a blank text file with nothing in it and with a 0 KB file size. The `.json` i was trying to use can be seen [here](https://u.teknik.io/Flsjd.json) and the result in the console after pressing `Compile` can be seen [here](https://p.teknik.io/Simple/WNHDM) and [here](https://u.teknik.io/6vt60.PNG).

**Comment by yanfali** [comment]
Sorry @jibreil my bad. It should be fixed in the next PR.

**Comment by jibreil** [comment]
Thanks @yanfali, seems to be fixed now 👍
