### ISSUE TITLE
[Feature Request] Generate a cheatsheet image

### ISSUE THREAD

**Issue by octref** [qmk/qmk_configurator#1083]
### Description

Hi there - love this project & thanks for your hard work!

I'd like to get a cheatsheet of my layout each time I update it. Found this on reddit:

![planck-layout](https://user-images.githubusercontent.com/4033249/154594108-3429804e-2f15-457c-ae64-334b27433d18.png)
 
Ideally, from a keymap.json, I get an image showing what's on layer 1/3/4/6.

One way of doing this would be rendering the layout to DOM, and use something like https://github.com/tsayen/dom-to-image to capture it.
I might be able to send a PR, if the maintainers see this as a worthwhile addition.

**Comment by yanfali** [comment]
Have you tried printing? There's a print button

**Comment by octref** [comment]
Just saw that, while it's a nice feature, I'd still love to have all info in one image...

**Comment by yanfali** [comment]
It's pretty difficult to fit all that in one keyboard. What if you had 10
layers?

**Comment by octref** [comment]
Yeah I don't think it'd apply to all use-cases, that's why I'm hesitant if this is a good addition to the configurator. I do guess 95% of the people use the 3 to 4 layers that's factory default, though. To those people this could be super useful.

**Comment by octref** [comment]
Seems some people already gave it a shot:
- https://github.com/brianoverby/OrthoKeymapSVG
- https://www.reddit.com/r/olkb/comments/oll0oi/create_you_own_planckpreonic_keymap/

**Comment by octref** [comment]
ok thanks!
