### ISSUE TITLE
Drop Menus Missing in Online Configurator[Bug] 

### ISSUE THREAD

**Issue by 01101001Dango** [qmk/qmk_configurator#1093]
### Describe the Bug

Hello folks,

Upon visiting the online configurator, I am met with an absence of the option to select a keyboard layout to configure and then download. I've tried the basics such as disabling my adblocker, disabling my antivirus, using a different browser, but I still don't see the drop menus for selecting the board. I feel like I'm missing something, but I may as well mention it here just in case anyone can tell me what I'm missing or if I'm not as insane as I think.

Thanks in advance!

### Additional Context?

![image](https://user-images.githubusercontent.com/72545899/156321295-802dac4e-ef4b-4e04-a177-c1ccc18a6200.png)

**Comment by yanfali** [comment]
Ah looks like the API cert is invalid. @skullydazed  can you please renew your certificate?

**Comment by wael444** [comment]
**I'M WAITING**

**Comment by svenschuldt** [comment]
The certificate seems to be valid now but the problem remains - am I doing something wrong?

![Screenshot 2022-03-03 at 06 21 18](https://user-images.githubusercontent.com/61102969/156501611-252dab3d-0d02-46e0-950d-7545ffc6d2f0.png)

![Screenshot 2022-03-03 at 06 20 49](https://user-images.githubusercontent.com/61102969/156501658-797d706c-bc8e-4453-b465-24ed14623a76.png)

**Comment by fauxpark** [comment]
No, the expired certificate is for keyboards.qmk.fm, not config.qmk.fm. The only person who is able to fix this has not been available yet. Please be patient, we'll update this issue when it is.

**Comment by svenschuldt** [comment]
Sure ... thanks for the update!

**Comment by fauxpark** [comment]
Seems like this is resolved now.
