### ISSUE TITLE
How to add a new keyboard item in Dropdown. Thank you very much

### ISSUE THREAD

**Issue by SEAN-JOU** [qmk/qmk_configurator#1110]
### Description

<img width="692" alt="截圖 2022-04-14 下午12 03 19" src="https://user-images.githubusercontent.com/25901493/163311497-48daea7b-4724-4e29-8875-df41e011b498.png">

### What do i prepare something to add it? Thank you very much

**Comment by noroadsleft** [comment]
QMK Configurator only supports keyboards with support merged in to [qmk/qmk_firmware's `master` branch](https://github.com/qmk/qmk_firmware/tree/master/).

Once you've done that, the instructions for adding a default keymap to QMK Configurator are here:

* [Adding Default Keymaps - QMK Firmware Documentation](https://docs.qmk.fm/#/configurator_default_keymaps)

**Comment by SEAN-JOU** [comment]
I am a keyboard maker.I want to add QMK firmware and  join the project for merging master.

**Comment by nooges** [comment]
Please see https://docs.qmk.fm/#/contributing
