### ISSUE TITLE
[Bug] GMMK Pro keymaps missing

### ISSUE THREAD

**Issue by lukini** [qmk/qmk_configurator#1124]
### Describe the Bug

If you select either GMMK Pro keyboard from the dropdown, there is no default keymap.  I believe this is because the existing maps (such as public/keymaps/g/gmmk_pro_ansi_default.json) are referencing the old path when the new ones have /rev1/ added to them.

**Comment by egreen0** [comment]
I am running into the same issue.

**Comment by noroadsleft** [comment]
Apologies for this. 

I haven't completed the branch that relocates the keymaps for the keyboards that have moved with this most recent `develop` branch merge. I should have it completed within a day or two.

I'm running behind because I was unwell all of last week.

**Comment by noroadsleft** [comment]
Confirming this issue is now fixed.
