### ISSUE TITLE
Missing some layer codes

### ISSUE THREAD

**Issue by drashna** [qmk/qmk_configurator#115]
Namely ~~`LT(x, kc)`, `LM(x, mod)`~~, `TO(x)`, and `TT(x)` are missing from the layer functions.

**Comment by yanfali** [comment]
yeah, these are all special. TO and TT should be easy
LT and LM are trickier

**Comment by yanfali** [comment]
@drashna can you create a separate bug for LT and LM please? I think we can close out TO and TT soon. The other two will require more thought.

**Comment by yanfali** [comment]
This one should be fixed now Thanks!

**Comment by drashna** [comment]
Sorry, yes! 

Closed.
