### ISSUE TITLE
Layers that are populated with layer activating keycodes such as TO don't turn bold when clicked

### ISSUE THREAD

**Issue by mechmerlin** [qmk/qmk_configurator#118]
Discovered while testing of PR #116.
Steps to reproduce
1. Use any keyboard/layout. 
2. Drag and drop TO and set it to a layer of your choosing. 
3. When clicking on the layer you set, a TRNS is put in the position of TO but the layer number doesn't get bolded. 

When exported and imported back in, the layer number is now bolded. 
If you don't click on that layer, it will lead to a compile error.

**Comment by yanfali** [comment]
@mechmerlin this should be resolved now. Thanks
