### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Duclh0403** [qmk/qmk_configurator#1188]
### Describe the Bug

I can't upload my file .json. When i upload it show:" Sorry, this doesn't appear to be a QMK keymap file." Can you help me ?

**Comment by fauxpark** [comment]
Pretty self explanatory. The file you're trying to upload is not a valid keymap JSON.

**Comment by noroadsleft** [comment]
What fauxpark said.

Post the JSON file you're trying to upload to this issue, or a link where we can read or download it.
