### ISSUE TITLE
[Bug] can't download firmware for ARM builds

### ISSUE THREAD

**Issue by Carlos-918** [qmk/qmk_configurator#1227]
### Describe the Bug

When ever trying to compile in the online configurator a planck/rev6 or planck/rev6_drop, an error(Firmware size check does not yet support STM32F303; skipping) appears. Even in the qmk default layout. No sure what is happening, maybe its me, but is kind of anoying that all the others work fine >:(  Just some days ago I used it and was perfectly fine. I don't know what is happening now. Please help :(

**Comment by tzarc** [comment]
That's not an error -- it'd work under normal circumstances.
There's a bug for all ARM builds -- with a fix incoming -- just need to sit tight while we sort it out.

**Comment by tzarc** [comment]
Should be fine, now. Can you please confirm?

**Comment by Carlos-918** [comment]
> Should be fine, now. Can you please confirm?

Yes, it works fine again. Thank you so much for the quick response.
