### ISSUE TITLE
[Bug] shambles file cannot compile

### ISSUE THREAD

**Issue by ThePandaxXx** [qmk/qmk_configurator#1245]
### Describe the Bug

Heya there, 

Trying to flash this keyboard and when I compile the default keymap an error message keeps popping up saying

config.qmk.fm.says
Unexpected error while compiling

Not doing anything unique or different, the keyboard itself isn't plugged in, just compiling the keymap and the error message pops up.

**Comment by keyboard-magpie** [comment]
This is not just shambles. Some issues with configurator after the breaking changes merge. Collaborator team are aware and working on it.

**Comment by ThePandaxXx** [comment]
> This is not just shambles. Some issues with configurator after the breaking changes merge. Collaborator team are aware and working on it.

AH alright that makes more sense, thank you.

**Comment by tzarc** [comment]
Try now.
