### ISSUE TITLE
[Bug] QMK Configurator produces .bin file (instead of .hex) for kinesis/kint41

### ISSUE THREAD

**Issue by negatv** [qmk/qmk_configurator#1253]
### Describe the Bug

QMK Configurator produces .bin file for kinesis/kint41, but cannot use this to flash the device.    Was able to produce a .hex file previously using the QMK Configurator.  

It looks like the following was removed from: qmk_firmware/keyboards/kinesis/kint41/rules.mk

FIRMWARE_FORMAT = hex

**Comment by tzarc** [comment]
Should be good, now.

**Comment by negatv** [comment]
Tested and verified to be working.
