### ISSUE TITLE
[Bug] Website not reflecting changes from firmware repo

### ISSUE THREAD

**Issue by GNOMES** [qmk/qmk_configurator#1255]
### Describe the Bug

Recently I raised this bug https://github.com/qmk/qmk_firmware/issues/20472, and it was soon fixed in https://github.com/qmk/qmk_firmware/pull/20476

This updated the files in the "default" keymaps directory seen here: https://github.com/qmk/qmk_firmware/tree/master/keyboards/gmmk/gmmk2/p65/ansi/keymaps/default

When visiting https://config.qmk.fm/#/gmmk/gmmk2/p65/ansi/LAYOUT, and load the default layout, I do not see this change reflected in the configurator.

Is this expected?

**Comment by zvecr** [comment]
Different process for configurator default keymaps.

Both
<https://github.com/qmk/qmk_configurator/blob/master/public/keymaps/g/gmmk_gmmk2_p65_ansi_default.json> and <https://github.com/qmk/qmk_configurator/blob/master/public/keymaps/g/gmmk_gmmk2_p65_iso_default.json> will need to be updated.
