### ISSUE TITLE
Big Switch exposes alignment issues

### ISSUE THREAD

**Issue by mechmerlin** [qmk/qmk_configurator#126]
When using the Big Switch with it's Big display: https://config.qmk.fm/#/bigswitch/LAYOUT

You get centered text when using keycodes like KC_A or even Backspace, but when you use something like MO, its centered but moved to the very top. They should all be centered.

**Comment by wojciechgabrys** [comment]
Proposed a fix in https://github.com/qmk/qmk_configurator/pull/534
