### ISSUE TITLE
Download Source is broken

### ISSUE THREAD

**Issue by mechmerlin** [qmk/qmk_configurator#130]
Even after compilation and the Download Source button turns green, nothing happens.

@skullydazed  reports that it works fine on the backend

noroadsleft reports that it sticks it in the console, so this is probably a front end error.

**Comment by noroadsleft** [comment]
I just tried this on a clean install of Firefox. Same behavior as my normal install. Chrome 66.0 64-bit is the same as well.

I am on Firefox 56.0.2 (64-bit), Windows 8.1. I can maybe try a current Firefox a bit later on this evening.

**Comment by yanfali** [comment]
not technically broken. Was never implemented.

**Comment by mechmerlin** [comment]
https://pixel.nymag.com/imgs/daily/selectall/2017/02/09/09-roll-safe.w710.h473.jpg

This works now.
