### ISSUE TITLE
[Bug] Bahrnob 65

### ISSUE THREAD

**Issue by cometiks** [qmk/qmk_configurator#1333]
### Describe the Bug

I flashed the keyboard and then the keybinds are misplaced on the board.

**Comment by noroadsleft** [comment]
There's nothing actionable here to work with. Misplaced how? What keys are where? Are you sure you have a Bahrnob 65?

**Comment by cometiks** [comment]
> There's nothing actionable here to work with. Misplaced how? What keys are where? Are you sure you have a Bahrnob 65?

Yes I do, but I realized after that it only offered flashing for the soldered pcb which was why it was misplaced and I have the hotswap.

**Comment by noroadsleft** [comment]
> I realized after that it only offered flashing for the soldered pcb which was why it was misplaced and I have the hotswap.

... I hate when the keyboard names don't make that clear.

A problem for future me, perhaps.
