### ISSUE TITLE
[Bug] Some magic keycodes are wrong (COMPILE ERROR)

### ISSUE THREAD

**Issue by kenblu24** [qmk/qmk_configurator#1352]
### Describe the Bug

Steps to replicate:
1. Go to https://config.qmk.fm/
2. Map any of the following keycodes from the "Keyboard Settings" tab:
  *  `LAG_SWP` (Swap LAlt/LGUI)
  *  `LAG_NRM` (Rev LAlt/LGUI)
  *  `RAG_SWP`
  *  `RAG_NRM`
  *  `GUI_ON` (Enable GUI)
  *  `GUI_OFF` (Disable GUI)
  *  `GUI_TOG` This one doesn't seem to be in QMK configurator.
  *  `LCG_SWP` (Swap LCtl/LGUI)
  *  `LCG_NRM`
  *  `RCG_SWP`
  *  `RCG_NRM`
  *  There may be more? IDK.
3. Attempt to compile (it should fail)

### Additional Context?

I found this commit which made these changes to QMK https://github.com/qmk/qmk_firmware/pull/19877/files#diff-de34b812c3592c84ece07d8cf6fb384c722c22353f09955421f502a9abdccad0

No idea if there are any other keycodes that fail.

**Comment by noroadsleft** [comment]
I knew there was something I needed to update but I couldn't remember what it was...

The keycodes in question got renamed a while back. I need to update Configurator's record of them.
