### ISSUE TITLE
[Feature Request] Desktop App

### ISSUE THREAD

**Issue by trymeouteh** [qmk/qmk_configurator#1354]
### Description

Please package this into a desktop application for Windows, MacOS and Linux to be able to run this app offline and easily be able to install the app from package repositories such as Scoop, Homebrew, Nix and Flathub.

Would recommend using Electron or Tauri.

**Comment by tzarc** [comment]
You can compile things yourself using normal QMK methods: https://docs.qmk.fm/newbs
If you wish to run things locally, you can stand up your own local copy using docker: https://github.com/qmk/qmk_web_stack

What you've specifically asked for it not in our roadmap and likely never will be. If you're keen on this sort of application, you'll be best off getting it going yourself.
