### ISSUE TITLE
Warn user if they're not running Firefox or Chrome

### ISSUE THREAD

**Issue by yanfali** [qmk/qmk_configurator#148]
We require ES6 and CSS Grid support for configurator. Warn the user if they are running a different browser that it may not be the best experience.

**Comment by gwerbin** [comment]
Confirmed that toolbox is unusable on IE 11. [Screenshot](https://i.imgur.com/jDTDAiz.png).

**Comment by yanfali** [comment]
Thanks for confirming

**Comment by yanfali** [comment]
Someone offered to work on this on discord, but haven't heard back since.

**Comment by zekth** [comment]
> Someone offered to work on this on discord, but haven't heard back since.

Is a banner at the top of the webapp good for Warn the user? i can adress that.

**Comment by yanfali** [comment]
Yeah that could work
