### ISSUE TITLE
Do not enable download firmware/source on a failed compile

### ISSUE THREAD

**Issue by yanfali** [qmk/qmk_configurator#151]
Reported by @NimMooMoo on discord.

**Comment by yanfali** [comment]
planck has this problem.

**Comment by skullydazed** [comment]
Disabling firmware download is a safe bet. However, would some users find it helpful to download source so they can debug failed builds easier? Or would we find it helpful when helping users debug?

**Comment by yanfali** [comment]
I would like that. Right now I believe it doesn't allow that. I would like to debug the planck build for example.

**Comment by noroadsleft** [comment]
I agree with yanfali. Being able to download source, even if invalid, would make debugging easier.

**Comment by douglas** [comment]
I would love this as well, but for `Ergodox Infinity` - In my case it is even simpler, I would love to download/see the generated `keymap.c` file so I can still use configurator but building the firmware locally.

**Comment by yanfali** [comment]
I think we have this now. Closing
