### ISSUE TITLE
default keymap name of "mine" cannot be easily deleted

### ISSUE THREAD

**Issue by mechmerlin** [qmk/qmk_configurator#157]
Using Chrome on macOS 10.13.4

When trying to delete "mine" by backspacing over one character at a time, starting from e, down to m. As soon as m is deleted, "mine" is shown again. The only way to properly delete it is to highlight "mine" and then delete. 

Coincidentally, this behavior is not consistent. If you have successfully made a keymap name such as 
"no_more_iso", highlighting it and deleting will generate "mine" again. 

This is quite annoying.

**Comment by yanfali** [comment]
Yeah, I'm aware of this behavior. I can look into changing it. The current work around is to select all and then start typing. it's to do with the reactive model checking the value. I think I can change it to allow empty and only substitute in mine if you leave it blank.

**Comment by yanfali** [comment]
OK, closing this as fixed.
