### ISSUE TITLE
Allow autocomplete in the dropdowns

### ISSUE THREAD

**Issue by skullydazed** [qmk/qmk_configurator#192]
It would be cool if you could click in the dropdowns and start typing, and have your choice autocompleted. It should match substrings within dropdown values so that you don't have to know what your selection starts with in the case of boards like `play/ca66`.

**Comment by yanfali** [comment]
https://github.com/moreta/vue-search-select is a possibility

**Comment by yanfali** [comment]
Resolved by 5b073c584f37fd4df62a5de27d0211429ca1e66d
