### ISSUE TITLE
Better Button Naming

### ISSUE THREAD

**Issue by mechmerlin** [qmk/qmk_configurator#194]
### Examples
For example, in the RGB section, we have buttons called RGB something something. 
- We can do Mode+ and Mode-. instead of RGB Mode +. After all we do have just Hue+ and Hue-
- Rather than RGB Mode B, we could just call it Breathe. 
- We could call RGB Mode R, just Rainbow. 

### Issues
There might be overlaps, if we ever do implement backlight breathing, then we would have two buttons labeled breathing. Hopefully people would be able to determine which is which because one is in the Backlight Section and one is in the RGB section. The same goes for Toggle.

**Comment by yanfali** [comment]
This should be resolved now by the addition of large tooltips.
