### ISSUE TITLE
Chibios compiling and downloading

### ISSUE THREAD

**Issue by yiancar** [qmk/qmk_configurator#195]
As I understand it the issue to get Chibios based boards is twofold.

Firstly, the backend does not support pulling the necessary git modules. For example Chibios, Chibios-Contrib etc. I imagine there should be a way for periodically to check those repos and pull when needed.

Furthermore I have been informed that for some reason the frontend cannot let you download .bin files (@yanfali has some suggestions on this).

I would consider this relatively critical to the support of STM32 based boards as most end users don't want to manually compile there firmware.

**Comment by yiancar** [comment]
I did not know that the API was not here:)

**Comment by yanfali** [comment]
No problem
