### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by jackhumbert** [qmk/qmk_configurator#2]
Setup a localisation system for strings

**Comment by yanfali** [comment]
I've looked into this a bit, and I think i18next.js is a good option, it works with both jQuery and all the popular UI frameworks.

**Comment by yanfali** [comment]
@mechmerlin you owe me a translation file for chinese. on branch yanfali:yanfali-i18n

**Comment by yanfali** [comment]
Plumbing implemented.
