### ISSUE TITLE
Only download keymap source

### ISSUE THREAD

**Issue by drashna** [qmk/qmk_configurator#213]
I'm not sure if it's due to technical limitations or what ..... but I feel that it's not intuitive or helpful to download the entire source from the configurator.

All we need is the keymap.c, rules.mk, and config.h from the keymap folder. Maybe the json, too. 

That way, users can just dump their files into a full qmk_firmware repo, and build that.  

The Ergodox EZ Configurator handles it this way (well, just the keymap.c), and it's easier.  And a much smaller download. 

Also, have you tried converting the contents of a zip to an actual local repo?   It's a nightmare (I haven't figured it out yet)

**Comment by yanfali** [comment]
With new configurator version, this issue should now be resolved.
