### ISSUE TITLE
Suggestion: new layers should only be saved if something is added to it

### ISSUE THREAD

**Issue by 1hella** [qmk/qmk_configurator#287]
I had the problem of a bunch of empty layers being created by clicking on them, which in my case gave an error during compilation.

I think just clicking a layer shouldn't save it. I suggest that if somebody clicks on a new layer, it should only be saved after a key is changed on it. In other words, when clicking away from a layer, if every key code is KC_NO, delete it.

Alternatively, having a button to delete an accidentally created layer would work as well.

**Comment by yanfali** [comment]
Yep thanks for raising issue. It's been on my list to add layer editing for a while so I will be working on this in the future.

**Comment by yanfali** [comment]
@1hella give the latest configurator a try. It should be working the way you expect. Thanks for the suggestion. We also support sparse layers, but the downside is the keymap generated will be larger, so this may cause problems for some keyboards.
