### ISSUE TITLE
Keymap presentation is broken for very tall keyboards

### ISSUE THREAD

**Issue by dudeofawesome** [qmk/qmk_configurator#3]
![image](https://user-images.githubusercontent.com/1683595/34904021-be4abc76-f7f1-11e7-90b9-d4f0261e3bf9.png)

It looks like it is assumed that a keymap will be no taller than the layer picker.

**Comment by yanfali** [comment]
I think the best way of dealing with this would be to add a info.json that overrides the default layout from the header files.

**Comment by yanfali** [comment]
This should be fixed with the current configurator. Thanks for reporting.
