### ISSUE TITLE
Potato facts: Solanaceous to Solanaceae

### ISSUE THREAD

**Issue by minjaesong** [qmk/qmk_configurator#311]
"Solanaceous" is an adjective; if you want to say the "Nightshade Family", your correct scientific word is "Solanaceae Family"

If you look at the [Wikipedia article](https://en.wikipedia.org/wiki/Solanaceae), they use "solanaceae" a lot, but "solanaceous" only occurs once (solanaceous flowers).

**Comment by yanfali** [comment]
Thanks. Want to submit a PR to fix it?
