### ISSUE TITLE
prevent people using more than additional 15 layers

### ISSUE THREAD

**Issue by yanfali** [qmk/qmk_configurator#329]
Don't allow a user to input more than 15 layers

**Comment by noroadsleft** [comment]
More than 16* layers (index 15).

**Comment by yanfali** [comment]
0 is always defined. So 15 is the maximum you can define

**Comment by yanfali** [comment]
Should be resolved now for built in keycodes. People can still abuse the ANY keycode, but it's not worth trying to fix that.
