### ISSUE TITLE
Reset 'active' layer to 0 on loading default

### ISSUE THREAD

**Issue by yanfali** [qmk/qmk_configurator#33]
If you are in the layer UI, and click load default, the active layer stays on the layer you last clicked on. It should reset to 0.

reproduce:

1. select planck keyboard
2. click layer (10)
3. load default

Symption:

layer 10 is still active but you are actually looking at layer 0.

**Comment by yanfali** [comment]
Also introduces extra layers empty layers which will cause problems for backend

**Comment by yanfali** [comment]
we can close this I think @jackhumbert

**Comment by jackhumbert** [comment]
Awesome - thanks :)
