### ISSUE TITLE
Two Click Keymapping

### ISSUE THREAD

**Issue by mechmerlin** [qmk/qmk_configurator#37]
This request comes from notG10, one of the moderators of the Top Clack Discord.

Click and dragging can be quite strenuous. It would be great to be able to select an empty/filled spot on the keyboard representation, and then click on a keycode you want. 

To be clear, this is not to get rid of the click and drag feature, but rather as another form of keycode entry.

**Comment by yanfali** [comment]
should be done. @mechmerlin can you confirm?

**Comment by mechmerlin** [comment]
Yes this work! Closing.
