### ISSUE TITLE
Cannot set kc for LT function

### ISSUE THREAD

**Issue by vanhtuan0409** [qmk/qmk_configurator#378]
Hi team, I appreciate your work here. But how can I specify the `kc` for LT function?
As right now, I can bind LT3 function to a key but `kc` value is always `N/A`

**Comment by yanfali** [comment]
Yeah sorry, you have to drag a code from keycodes onto the UI. I will work on making this better.

**Comment by vanhtuan0409** [comment]
oh tks you for the tip :D
I have no problem with dragging. Maybe we can just document it somewhere for a new user like me

**Comment by yanfali** [comment]
You are totally correct. I think we need an onscreen tip. I will try to think something up.
