### ISSUE TITLE
[chore] Style refactoring

### ISSUE THREAD

**Issue by zekth** [qmk/qmk_configurator#405]
In the projects styles are a bit mixed, a bit too much. There is:
- ./public/style.css
- ./src/scss/*.scss
- non scoped style in components

To be more consistent i think it's better to write everything non scoped in `./src/scss/*.scss` and scoped in the components itself.

I can tackle this. Your thoughts?

**Comment by yanfali** [comment]
Sure, if you and @noroadsleft want to take a stab at this, I'm good with that. Scoped classes are a good idea, but they have some drawbacks too.

**Comment by zekth** [comment]
has been merged. Closing
