### ISSUE TITLE
Allow environment variable override for backend_baseurl

### ISSUE THREAD

**Issue by cscheib** [qmk/qmk_configurator#413]
it's OK that we hardcode backend_baseurl as a constant, but we need a way to override it during development without having to manually edit the config file.

This will be particularly useful for the docker-compose web stack at https://github.com/qmk/qmk_web_stack

**Comment by cscheib** [comment]
https://github.com/qmk/qmk_configurator/blob/e84633a9cc8489da8095d587618d2520b0bdc601/src/store/modules/constants.js#L3

**Comment by yanfali** [comment]
well a javascripty way to deal with this is take advantage of process.env.NODE_ENV. Check it for production and use one value, for anything else, just use an environment variable if it exists.

**Comment by yanfali** [comment]
@zekth you want to take a stab at this one?

**Comment by cscheib** [comment]
@yanfali I may take a crack at it myself, once I finish with a couple other tasks I'm working on.  Whoever gets to it first.

I'm not sure I'd interpret NODE_ENV for this one -- there may be some valid reason for someone to run one of these of their own, so why not just default to api.qmk.fm (as-is) and if-and-only-if the environment variable exists, use the value of that.  I personally believe NODE_ENV tends to be abused by node devs

**Comment by yanfali** [comment]
@cscheib we mostly use NODE_ENV for build time stuff, there's some code to selectively replace files for google analytics we aren't using anymore that would do what you are after. However since this is actually a dev only feature, environment variables are appropriate.
