### ISSUE TITLE
[chore] refactor startup ordering

### ISSUE THREAD

**Issue by yanfali** [qmk/qmk_configurator#414]
Right now the logic for startup is spread out across a bunch of different components.
There are at least 2 aspects:

mounted - when the page initially loads - parsing URL parameters
watch - when someone actively changes a URL

components are doing this in multiple places.

TODO: move responsibility into App.vue/Main.vue and use properties on components to update behavior. Having this logic distributed is not maintainable.

**Comment by zekth** [comment]
Totally agree with this. App statement as to be handled in the APP and not throught all the components.
