### ISSUE TITLE
keep list of user's favorite keyboards in local storage and filter UI

### ISSUE THREAD

**Issue by yanfali** [qmk/qmk_configurator#424]
Users would be able to pick which keyboards they prefer to see in their drop down, and toggle this on and off. Maybe have a :heart: icon which a user would click to add it to list and a :filter: icon to toggle the feature on and off.

Because all data is stored in the browser and never sent anywhere else this should not contravene GDPR because there is no PII (Personally Identifiable Information) beyond a simple list of keyboards in local storage, and possibly the layout.

**Comment by zekth** [comment]
This may be done after the refactor involved by https://github.com/qmk/qmk_configurator/issues/415 ?

**Comment by yanfali** [comment]
That's probably a good idea.
