### ISSUE TITLE
Render ISO enter keys correctly in keymap

### ISSUE THREAD

**Issue by yanfali** [qmk/qmk_configurator#43]
Because they aren't rectangles, they don't render quite right.

![screen shot 2018-04-06 at 09 34 08](https://user-images.githubusercontent.com/2275667/38432845-acec2c3a-397d-11e8-8b44-6a6eeb88969f.png)

Figure out a way to add the extra bit.

**Comment by fauxpark** [comment]
Looks like this has been done.
