### ISSUE TITLE
Iris v3 cursor keys don't seem to work

### ISSUE THREAD

**Issue by emanpatricio** [qmk/qmk_configurator#439]

**Comment by emanpatricio** [comment]
What am I doing wrong the HJKL, when configured as an arrow for layer 1, it's not working as expected. 

this is the config
https://imgur.com/kNTbpcr

**Comment by noroadsleft** [comment]
That should work as long as you're holding down the `MO(1)` key while attempting to use the HJKL arrows.

**Comment by emanpatricio** [comment]
Sorry for the late replied, I really don't know what I'm doing wrong, but I had an opportunity to try again this afternoon, the Numpad on MO(1) is not getting overwritten.

Tonight I will try with my rev3 keebio hopefully, it will work.

**Comment by yanfali** [comment]
@emanpatricio in your screen shot you'd selected the iris v2. That has an incompatible matrix with the rev3 so it probably won't work. Please try again with a rev3 

https://config.qmk.fm/#/keebio/iris/rev3/LAYOUT

**Comment by yanfali** [comment]
No response in 14 days. Closing. Please reopen if this is still an issue.
