### ISSUE TITLE
Inputting Arbitrarily High Layer Value crashes UI

### ISSUE THREAD

**Issue by earthbound2eric** [qmk/qmk_configurator#450]
typing in an arbitrarily large number into the momentary layer change key will cause the site to crash.

**Comment by yanfali** [comment]
@earthbound2eric nice catch. Can you test this please? 

http://test.config.qmk.fm

It should be fixed there.

**Comment by zekth** [comment]
LGTM

**Comment by noroadsleft** [comment]
LGTM2

**Comment by yanfali** [comment]
@earthbound2eric should be fixed. Please re-open if this is still an issue.
