### ISSUE TITLE
Check for browser features instead of browsers in browser warn?

### ISSUE THREAD

**Issue by xster** [qmk/qmk_configurator#495]
It wasn't very clear why a warning banner was shown on Safari. Looking at https://github.com/qmk/qmk_configurator/issues/148, it doesn't really seem like the warning applies. Perhaps use browser feature detection instead of whitelisting browser types.

**Comment by yanfali** [comment]
Sorry, we don't have a big enough team to support Safari. We only support two browsers officially, Firefox and Chrome.
