### ISSUE TITLE
Provide means to download .bin file

### ISSUE THREAD

**Issue by mechmerlin** [qmk/qmk_configurator#52]
On keyboards such as the whitefox, flashing is done by doing
```
dfu-util -D ../../.build/whitefox_default.bin  -S mk20dx256vlh7
```

The QMK Configurator currently has no means to download the required .bin file.

**Comment by yanfali** [comment]
Ditto for clueboard 60.

**Comment by yanfali** [comment]
Looking at the code, this is actually built into the backend, so the front end is ready mostly for when the backend can do this. We may want to change the name of the download button based on metadata we know about the board.

**Comment by yanfali** [comment]
Talked this over with @skullydazed and it looks like we can already handle this via the API. I'm going to file a new enhancement bug to rename the download hex button to download firmware.

**Comment by holtenc** [comment]
I see this change has been implemented, but for the TADA68 it still downloads a HEX instead of a BIN

**Comment by yanfali** [comment]
Nope. Sorry. Waiting in all changes still.

**Comment by jibreil** [comment]
@yanfali any idea if/when this functionality will be implemented, myself and others are looking for an easy way to get the `.bin` for a TADA68 without manually building QMK via the command line.

**Comment by yanfali** [comment]
@jibreil hopefully in the near future. @skullydazed is a bit busy right now, but hopefully he can get it over the line once he's freed up. It's mostly a backend issue as the front end doesn't have control over what bits are sent over the API.

**Comment by jibreil** [comment]
@yanfali 👍
