### ISSUE TITLE
Add `Brightness Up` and `Brightness Down` keycodes

### ISSUE THREAD

**Issue by QQism** [qmk/qmk_configurator#535]
It would be very handy for laptop users to adjust their internal screen brightness by adding brightness up and down keycodes (i.e. `KC_BRIGHTNESS_UP` and `KC_BRIGHTNESS_DOWN),` to the UI configurator `/store/modules/keycodes/app-media-mouse.js`. 

The keycodes work on both Windows 10 and macOS High Sierra 10.13 from what I've tested and should be fine with their later OS versions.

Please let me know if this is a good idea 😁

**Comment by yanfali** [comment]
@QQism not against it, send a PR and work with @noroadsleft on where to put it

**Comment by noroadsleft** [comment]
Solved in #538.
