### ISSUE TITLE
Unchangeable shortcuts: Control+Backspace deletes a word. Alt+Backspace undo.

### ISSUE THREAD

**Issue by iopred** [qmk/qmk_configurator#60]
I'm compiling the ORG60 firmware and the control+backspace shortcut is very frustrating.

**Comment by mechmerlin** [comment]
Can you provide more details on how you are using the Ctrl and Backspace shortcut.

**Comment by iopred** [comment]
My config just has Right/Left Ctrl and Backspace set like normal. But when I use Ctrl+Backspace it deletes a full word.

My full config can be found here: https://pastebin.com/M5LfU7wm

**Comment by skullydazed** [comment]
Hi @iopred. If I understand the situation correctly I don't think this is anything QMK is doing. When you press Ctrl-Backspace in Windows the default action is to delete a whole word. If you have another keyboard you can verify this behavior by typing Ctrl-Backspace on that keyboard and see that the same thing happens.

If I've misunderstood the situation and you do have a problem with how your keyboard is behaving after flashing a hex you downloaded from the configurator, the best place to get help with that is here:

https://github.com/qmk/qmk_firmware/issues
