### ISSUE TITLE
strange qEvt() appears on the source code

### ISSUE THREAD

**Issue by yulei** [qmk/qmk_configurator#623]
while I try to compile the [noah](https://config.qmk.fm/#/matrix/noah/LAYOUT_wkl) keyboard, I got the following error:
![image](https://user-images.githubusercontent.com/720475/70767765-78ae9600-1d9d-11ea-9ed4-9314e582613d.png)

so I downloaded the source code and found 
![image](https://user-images.githubusercontent.com/720475/70767825-a3005380-1d9d-11ea-9502-f1d622a1a4f0.png)

the macro qEvt() was not from the chibios os, it was auto-generated and then inserted to the source codes? there should be some bugs which caused the macro inserted into line 934 lost one parameter.  Maybe a counter overflow? I have attached the file which caused the trouble.
[hal_i2c_lld.c.txt](https://github.com/qmk/qmk_configurator/files/3958939/hal_i2c_lld.c.txt)

**Comment by yanfali** [comment]
@yulei was this fixed?

**Comment by noroadsleft** [comment]
Looks fixed.

![image](https://user-images.githubusercontent.com/18669334/75836800-db4d7780-5d77-11ea-8b27-47bccdb7ca00.png)
