### ISSUE TITLE
Bug/Error when compiling new keymap for Matrix Noah

### ISSUE THREAD

**Issue by agbubby12** [qmk/qmk_configurator#655]
As the title says, I am attempting to flash a new Matrix Noah and seem to be getting an error everytime I try to compile the keymap I want. Not sure what is going on because this is like my 2nd time using QMK, but I can attach the entire code I get here: 

[noah eror.txt](https://github.com/qmk/qmk_configurator/files/4189297/noah.eror.txt)

For context I am selecting matrix/noah as the keyboard and using the LAYOUT_default. Please let me know what other information I can give.

**Comment by yanfali** [comment]
I've tested the docker container and it doesn't fail, so I'm not sure what's going here. It could be something to do with the version of the source pulled down by the API being out of date.

**Comment by yanfali** [comment]
Looks like this fix is needed: https://github.com/qmk/qmk_compiler/pull/59

**Comment by skullydazed** [comment]
This should be working now that I've pushed out https://github.com/qmk/qmk_compiler/pull/59. I was able to compile an empty layout just now.
