### ISSUE TITLE
Numpad in Keycode Selection is Missing 3

### ISSUE THREAD

**Issue by mechmerlin** [qmk/qmk_configurator#66]
![qmk config numpad](https://user-images.githubusercontent.com/30334081/39024259-8c28d67a-43f4-11e8-84ce-2607b5183271.png)

It's missing 3!!!

Thank you to isabella on the r/mk discord for reporting.

**Comment by yanfali** [comment]
haha, it was actually correct before from the code perspective, but it's always said 4. 4 is unlucky in asian countries.

```diff
-      { name: '1', code: 'KC_P1' },
-      { name: '2', code: 'KC_P2' },
-      { name: '4', code: 'KC_P3' },
+      { name: '1', code: 'KC_P1', keys: 'num_1' },
+      { name: '2', code: 'KC_P2', keys: 'num_2' },
+      { name: '4', code: 'KC_P3', keys: 'num_4' },
```

**Comment by mechmerlin** [comment]
Can confirm.
