### ISSUE TITLE
Whole body moves while dragging (& can't push to new branch)

### ISSUE THREAD

**Issue by robinrabauke** [qmk/qmk_configurator#668]
Hi,

I've realised that the whole body moves slightly to the right while I drag a key from the keyboard to the keymap. This also makes it hard to actually drag a key.

I've reintroduce the class `.hidden` to actually hide the drag-container, which works but I can't push to the repository.

What do I need to do to be able to create a branch and a PR?

best, robin

**Comment by yanfali** [comment]
yeah, PR. https://opensource.com/article/19/7/create-pull-request-github
What projects let you push code to them without permissions?

**Comment by yanfali** [comment]
@robinrabauke please close issue after you've verified it's fixed for you

**Comment by robinrabauke** [comment]
> @robinrabauke please close issue after you've verified it's fixed for you

I was not aware that I need to fork it. Makes total sense now :) Thanks for the clarification!
