### ISSUE TITLE
~~keymap download broken~~ Remove download source and keymap.c functionality

### ISSUE THREAD

**Issue by elmo-space** [qmk/qmk_configurator#677]
Downloading the compiled keymap doesn't work anymore right now.
Instead of downloading a zip file with the keymap.c the "keymap only" button gives you the same file as the "keymap json" download button, just with a different filename.
The generated keymap.c is also missing when downloading the full source as well.

**Comment by skullydazed** [comment]
This is a new change. You can compile JSON files using the CLI and have been able to for some time. The API has been changed to use that facility instead of generating a keymap.c, so it's delivering the keymap source as used.

**Comment by yanfali** [comment]
That means the UI is broken. Re-opening and renaming the bug

**Comment by yanfali** [comment]
ok. discussed this offline. @skullydazed will be opening an issue in future to aggregate future changes for the UI. closing for now.
