### ISSUE TITLE
Render the README instead of showing source

### ISSUE THREAD

**Issue by colemarkham** [qmk/qmk_configurator#69]
Currently the source is shown for the keyboard README. Many users will not understand the formatting, and most would prefer to see the rendered version.

**Comment by yanfali** [comment]
Hi @colemarkham we actually had a prototype that rendered this using a markdown library, but @jackhumbert preferred having the text always be on screen. We're looking at redesigning the layout and there may be a possibility to revisit this.

**Comment by yanfali** [comment]
I think we'll wait for the UI redesign. We can move this into a tab
