### ISSUE TITLE
Should be able to type in keycodes

### ISSUE THREAD

**Issue by skullydazed** [qmk/qmk_configurator#7]

**Comment by mechmerlin** [comment]
This is not a reference to the "Any" key form of inputting keycodes. 

A user should be able to click on a key in the layout and hit a key on their keyboard to set it. This is very similar to bootmapper client's way.

**Comment by yanfali** [comment]
@skullydazed @mechmerlin can you check out the latest version of configurator? We've added keypress support. Select keymap item first then push the key you want to assign. It should work on chrome and firefox.

**Comment by yanfali** [comment]
I think we have this working now. @mechmerlin does this one seem done to you?

**Comment by yanfali** [comment]
Done I believe
