### ISSUE TITLE
Import json file should split at the extension

### ISSUE THREAD

**Issue by mandeep** [qmk/qmk_configurator#719]
When importing a json file from disk, the keymap name is populated with the filename including the extension. E.g. `keymap.json` is populated into the keymap name field as `keymap.json`. This means when you export this keymap after making changes, the filename is output as `keymapjson.json`. Instead this should be `keymap.json` again. 

A fix for this would to split at the extension when importing such that a filename of `keymap.json` is populated in the name field as `keymap`.

**Comment by yanfali** [comment]
reproduced. Thanks!

**Comment by noroadsleft** [comment]
Good spot, @mandeep; thanks for reporting!
