### ISSUE TITLE
Compilation error on default layout for: ymdk_np21/LAYOUT_ortho_6x4

### ISSUE THREAD

**Issue by philipmgrant** [qmk/qmk_configurator#744]
Compiling the default layout for ymdk_np21/LAYOUT_ortho_6x4 fails with:

```
error: pathspec 'lib/vusb' did not match any file(s) known to git
make: *** ine] Error 1
```

This seems to be fairly new: my own layout for this board compiled fine on QMK Configurator on 30th May but fails now.

**Comment by noroadsleft** [comment]
There is currently a known issue with Configurator not being able to compile firmware for boards that use V-USB – namely, anything powered by an atmega32a, atmega328, atmega328p, or attiny85. The ymdk_np21 is powered by an atmega32a.

We are working on a fix, but it hasn't been deployed yet.

**Comment by noroadsleft** [comment]
This is now fixed.

**Comment by philipmgrant** [comment]
Works perfectly now - thanks very much!
