### ISSUE TITLE
Feature: Set the whole layer to KC_TRNS

### ISSUE THREAD

**Issue by sigprof** [qmk/qmk_configurator#746]
The configurator currently has a “Clear layer” button, which sets the whole layer to `KC_NO`. However, in many cases setting the whole layer to `KC_TRNS` would be even more useful, and there seems to be no way to do it currently without repeated clicking.

**Comment by yanfali** [comment]
This is by design. @jackhumbert reasoned that KC_TRNS was too confusing as a default for newbs. KC_TRNS is really needs explanation. Principle of least astonishment.

**Comment by yanfali** [comment]
I think a compromise would be to have a toggle in settings which can flip the behavior
