### ISSUE TITLE
ymd/rev 2

### ISSUE THREAD

**Issue by SlickRickolus** [qmk/qmk_configurator#749]
There seems to be a problem when compiling a ymd75/rev2 hex file. wish i could say more but i have no idea what is going on.
![Annotation 2020-06-16 004056](https://user-images.githubusercontent.com/66993458/84745882-0f852680-af6a-11ea-94a4-f21204258a8d.png)

**Comment by noroadsleft** [comment]
This is caused by a bug with the Configurator's API. It detects the microcontroller incorrectly.

I have a workaround planned for later today but I haven't filed it yet.

**Comment by noroadsleft** [comment]
Solved by https://github.com/qmk/qmk_firmware/pull/9452.
