### ISSUE TITLE
suddenly I can't compile anymore!

### ISSUE THREAD

**Issue by ejahglass** [qmk/qmk_configurator#750]
I was making changes to my keymap, everything has been working fine with all the changes i have made over the last couple days, then I went to compile my last edits and I got

"
$ qmk compile
INFO Compiling keymap with make massdrop/alt:ejahglass

QMK Firmware 0.9.10
Making massdrop/alt with keymap ejahglass

/bin/sh: arm-none-eabi-gcc: command not found
sh: arm-none-eabi-gcc: command not found
sh: arm-none-eabi-gcc: command not found
make[1]: *** [tmk_core/rules.mk:263: gccversion] Error 127
Make finished with errors
make: *** [Makefile:584: massdrop/alt:ejahglass] Error 1
"

Please help, I have tried reinstalling MSYS2 twice now and I'm still getting the same error every time I try to compile.

**Comment by noroadsleft** [comment]
Did you get this figured out? (I know it's not a qmk_configurator issue, but I wanted to make sure.)
