### ISSUE TITLE
nested two-parameter keycodes fail to compile

### ISSUE THREAD

**Issue by Pawnerd** [qmk/qmk_configurator#76]
For instance, when I put a LGui_T inside a Rctl_T keycode, the compiler comes back with an error. I think it should be impossible to put two-parameter keycodes inside another two-parameter keycode? Picture to illustrate below:

![afbeelding](https://user-images.githubusercontent.com/1347264/39339383-d43cc3e8-49c8-11e8-9f57-1c48fb4a57e9.png)

**Comment by Pawnerd** [comment]
happy to help :)

**Comment by yanfali** [comment]
@Pawnerd is this still an issue?

**Comment by Pawnerd** [comment]
@yanfali Looks like it's fixed in the version that's running on config.qmk.fm 👍

**Comment by yanfali** [comment]
@Pawnerd feel free to close the issue then. Thanks again.
