### ISSUE TITLE
Error in configurator

### ISSUE THREAD

**Issue by Crankatator** [qmk/qmk_configurator#763]
I'm getting this error:
![image](https://user-images.githubusercontent.com/67513446/85926156-61cc1e80-b86b-11ea-93d4-cf6eb121612e.png)
 for this keymap:
![image](https://user-images.githubusercontent.com/67513446/85926171-7f998380-b86b-11ea-97c9-fb1ad8bfc651.png)
The suggested "}" doesn't make sense.  What's going on?

**Comment by yanfali** [comment]
Hey are you using cli? File the bug under firmware. But honestly I think you have a typo in your code. It's kc_lctl not kc_lctrl

**Comment by noroadsleft** [comment]
> I'm getting this error:
> [image](https://user-images.githubusercontent.com/67513446/85926156-61cc1e80-b86b-11ea-93d4-cf6eb121612e.png)
> for this keymap:
> [image](https://user-images.githubusercontent.com/67513446/85926171-7f998380-b86b-11ea-97c9-fb1ad8bfc651.png)
> The suggested "}" doesn't make sense. What's going on?

Line 8 of your `keymap.c`, you're missing a comma after `KC_DEL`.


> I think you have a typo in your code. It's kc_lctl not kc_lctrl

For the record, either should work.

https://github.com/qmk/qmk_firmware/blob/751a1789b59546728c0987d9259b4189cd9f6fe2/tmk_core/common/keycode.h#L153

**Comment by Crankatator** [comment]
Thanks for your help!
