### ISSUE TITLE
Why not render unassigned keys blank on PDF printout?

### ISSUE THREAD

**Issue by coaxial** [qmk/qmk_configurator#769]
Unassigned keys are marked N/A on the PDF document for printing. Wouldn't it be more legible if the unassigned keys were left blank?

It would not only save on toner/ink but also make it much easier to scan secondary layers where only a small number of keys are assigned.

**Comment by yanfali** [comment]
That seems reasonable. It could be done with some CSS using the print style sheet, just make the N/A keys class hidden when printing.
