### ISSUE TITLE
Where are layouts stored?

### ISSUE THREAD

**Issue by iandoug** [qmk/qmk_configurator#788]
HI

I need to add a new physical layout, but can't find where they are stored. I've done text searches etc on local copy and here.

Can you please advise? :-)

Thanks, Ian

**Comment by noroadsleft** [comment]
@iandoug,

QMK Configurator takes its data through an API that runs based upon the current state of https://github.com/qmk/qmk_firmware/tree/master/. If you need to add a physical layout, it needs to be done on that repo.

Which keyboard and layout do you need to add?

**Comment by iandoug** [comment]
Okay let me poke around in the firmware repo then, thanks.

Trying to build this (still... :-) )
https://www.keyboard-design.com/letterlayout.html?layout=x6-5h.en.ergolinear

I haven't tried to get the configurator running locally yet ... will that also pull from the net, or look for a local source?

Thanks, Ian

**Comment by noroadsleft** [comment]
Ah, a new device.

You'll have to have your codebase merged into qmk/qmk_firmware generally to support a new keyboard. You can also feed it custom API data if you deploy the Configurator in Docker, but I have no experience with that.

**Comment by iandoug** [comment]
When I last dipped my toes into QMK a few years back, I vaguely remember some "battleship" layouts that catered for x rows by y columns, where x and y are larger than normal ANSI. Are those still in the configurator?

BTW my mind works the other way around to the configurator... first pick physical layout, and then logical. At the moment once you pick logical, the physical options are restricted, so there is no easy way to browse the physical variants available.

Or maybe I'm missing something obvious ...

Thanks, Ian

**Comment by yanfali** [comment]
I think this conversation has been resolved. Closing issue.
