### ISSUE TITLE
Download "keymap only" button and feature removed?

### ISSUE THREAD

**Issue by dainkaplan** [qmk/qmk_configurator#792]
There used to be a button to download the keymap config so you can compile locally and edit the `keymap.c` and `config.h` files (it's still in the i18n csvs as a label), but it looks to be removed in 
 commit f67c15f92ac52553c67cb9ac5353f31a267d99c0 (via issue #692):

![image](https://user-images.githubusercontent.com/594193/90263883-3ccb5380-de8b-11ea-82cf-a7f96f4505c8.png)

Downloading the entire source doesn't seem to include the keymap config, so there is now no way to get the config files to modify them.

What I see:
![image](https://user-images.githubusercontent.com/594193/90264138-9cc1fa00-de8b-11ea-9351-e9a75ea00fd7.png)

What the tutorial video shows (and what used to also show previously):
![image](https://user-images.githubusercontent.com/594193/90264198-b4997e00-de8b-11ea-9188-f04f3c8de033.png)

**Comment by yanfali** [comment]
https://github.com/qmk/qmk_configurator/issues/784

**Comment by yanfali** [comment]
@skullydazed did you remove the json file from the full source download?

**Comment by noroadsleft** [comment]
> did you remove the json file from the full source download?

JSON file is in the root `qmk_firmware` directory inside the Full Source download.
