### ISSUE TITLE
Potential Security Notification

### ISSUE THREAD

**Issue by mrsendyyk** [qmk/qmk_configurator#793]
Hello, i found this on my notifications:
![Screenshot_2020-08-17 Build software better, together](https://user-images.githubusercontent.com/69058604/90342090-9ec4be00-e02f-11ea-8bf6-597ed6226416.png)
It needs to be fixed?

**Comment by yanfali** [comment]
These are automated, and apply only to your fork. Configurator is already patched and up to date. Thanks

**Comment by mrsendyyk** [comment]
Ok, thank you @yanfali
