### ISSUE TITLE
layout reset prompt when returning from "print keymap" or "test keyboard"

### ISSUE THREAD

**Issue by slashfoo** [qmk/qmk_configurator#796]
When using a custom layout configured in the browser (not selected from a dropdown), from the "Test keyboard" window, or "Print keymap: window; when you press "< Back", the screen goes to the main interface, but attempts to clear the layout that's currently being worked on with a prompt that reads "This will clear your keymap - are you sure you want to load default keymap?"

**Comment by slashfoo** [comment]
Additionally, when pressing cancel to avoid resetting the layout, the keymap name is still lost.

**Comment by noroadsleft** [comment]
@yanfali Would you mind looking at this?
