### ISSUE TITLE
Uploading default keymap.json to hhkb/ansi isn't recognized

### ISSUE THREAD

**Issue by alexytlee** [qmk/qmk_configurator#801]
I get a 'Sorry, this doesn't appear to be a QMK keymap file.' even though it was downloaded from the page.

**Comment by noroadsleft** [comment]
Was this a keymap you modified in Configurator then exported?

You can upload the file to this issue by giving it a `.txt` file extension.

**Comment by alexytlee** [comment]
Seems issue was fixed!
