### ISSUE TITLE
unable to flash

### ISSUE THREAD

**Issue by dburnnzz** [qmk/qmk_configurator#802]
i am unable to flash the PCB, it keeps telling me no devices found. i have a dzrgb v2. i have tried reinstalling the drivers and the only one that works is the atmel 32u4

**Comment by noroadsleft** [comment]
@dburnnzz This isn't a QMK Configurator issue, but put your board in Bootloader Mode and Install Drivers (right-click the blank area to the left of the flash button). There should be a gold button on the bottom of your PCB to put the board in bootloader, next to the spacebar switch.

![image](https://user-images.githubusercontent.com/18669334/91656533-43062600-ea6e-11ea-8bfb-b9bae57e68e6.png)

**Comment by yanfali** [comment]
I think this has been resolved.
