### ISSUE TITLE
Rotary Encoder Not Functioning as Arrows

### ISSUE THREAD

**Issue by jessekirbs** [qmk/qmk_configurator#805]
I'm attempting to get my two rotary encoders to function as UP/DOWN and LEFT/RIGHT arrow keys. I've tried using KC_UP, KC_DOWN, KC_LEFT, and KC_RIGHT in my keymap, but they don't seem to do anything. Any help would be greatly appreciated. Thank you!

**Comment by jessekirbs** [comment]
I may have found the solution - thank you.

**Comment by isaacsanders** [comment]
what did you see?
