### ISSUE TITLE
Scaling doesn't reset when importing keymaps on Firefox.

### ISSUE THREAD

**Issue by FrostByte-Dev** [qmk/qmk_configurator#82]
If on a larger board that is scaled down to fit such as the converter/ibm_terminal when importing a smaller keyboard such as the dz60 it does not scale back up. Seems to only affect firefox.

**Comment by yanfali** [comment]
@FrostByte-Dev this one ok now?

**Comment by FrostByte-Dev** [comment]
Looks to be working now.
