### ISSUE TITLE
DZ96 PCB

### ISSUE THREAD

**Issue by CptSpirit** [qmk/qmk_configurator#837]
Still no official DZ96 board on the configurator, this is the board used in the tofu96.

**Comment by yanfali** [comment]
@moyi4681 anything to comment about this?

**Comment by noroadsleft** [comment]
https://github.com/qmk/qmk_configurator/issues/734#issuecomment-631351156

Use [Espectro](https://config.qmk.fm/#/espectro/LAYOUT_default) – it's the same PCB.

(We could probably stand to move it on QMK Firmware. The Espectro was by mechkeys.ca, which no longer operates.)
