### ISSUE TITLE
'Unknow error' ISO KBD67 MKii soldered

### ISSUE THREAD

**Issue by FruitLoopsGB** [qmk/qmk_configurator#838]
Trying to compile and an unknown error occurs every time.
[
![Issue](https://user-images.githubusercontent.com/74061216/98379447-36d6b000-203f-11eb-815b-bfacad334bff.PNG)
](url)

**Comment by noroadsleft** [comment]
We had some issues this past week with the infrastructure on which the Configurator runs – you may have been trying to compile during that time. I tried compiling this board and can't reproduce this issue now.

Sorry for the troubles, either way.

**Comment by ostap-tymchenko** [comment]
Hi! im getting this issue for 2 days now, and i cant compile anything. It started late last night/ early morning est.
![image](https://github.com/qmk/qmk_configurator/assets/56374185/be8f474e-a31f-4620-ae7c-97b5edd844b8)

**Comment by keyboard-magpie** [comment]
Much the same as per noroadsleft's message on Nov 8 2020, we've just had a breaking changes cycle so some things require updating. The team are [working on it](https://github.com/qmk/qmk_firmware/pull/22555).
