### ISSUE TITLE
KBD19X Missing Objects for VIA Design

### ISSUE THREAD

**Issue by bvbowes** [qmk/qmk_configurator#840]
Exported a JSON file from online QMK and when imported to JSON in VIA its missing the following:
Object: should have required property 'layouts'
Object: should have required property 'lighting'
Object: should have required property 'matrix'
Object: should have required property 'productid'
Object: should have required property 'vendorId'

**Comment by yanfali** [comment]
Sorry these projects are not compatible. Via has their own proprietary format. You'll need to check their docs for details.

**Comment by noroadsleft** [comment]
@bvbowes You need to follow the VIA Docs: https://caniusevia.com/docs/specification

VIA JSON files go here: https://github.com/the-via/keyboards/tree/master/src
