### ISSUE TITLE
Print Keymap is blank if one of your layers is empty

### ISSUE THREAD

**Issue by MaxKablaam** [qmk/qmk_configurator#852]
I have layers 0-1 set up, 2 is blank (everything is N/A), and layers 3-6 are full. When I press print keymap I get a blank screen. I was able to get a keymap to print when I filled layer 3.

I'm purposely leaving 3 empty so that I can put another layout there in the future.

**Comment by noroadsleft** [comment]
Confirmed.

As a work-around, you can still get to the preview if you clear the layer and then go to the Print view while the cleared layer is the active layer in the interface. Obviously doesn't work if you clear more than one layer.
