### ISSUE TITLE
[feature request] Be able to disable LEDs by default

### ISSUE THREAD

**Issue by toddnguyen** [qmk/qmk_configurator#858]
In the source, I can disable LEDs by default by modifying the rules.mk, but I can't do the same in the configurator web interface.

BACKLIGHT_ENABLE = no      # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no       # Enable keyboard RGB underglow

Can we have a way to do this in the web interface as well?

**Comment by toddnguyen** [comment]
If this is the same as #639, feel free to close this.

**Comment by yanfali** [comment]
All I can say is it's being worked on by the CLI team. I just have no ETA. Thanks for your input.
