### ISSUE TITLE
Compile error - fatal error: version.h: No such file

### ISSUE THREAD

**Issue by syepes** [qmk/qmk_configurator#872]
This is my fist try at building my own layout and I am getting the below error.
Does anyone know if this is a bug or am I doing something wrong?

![image](https://user-images.githubusercontent.com/333081/104828255-90d9ca00-5867-11eb-97f1-3b83a83063c8.png)
I have attached the layout: [syepes.zip](https://github.com/qmk/qmk_configurator/files/5825374/syepes.zip)

Thanks in advance for any help

**Comment by skullydazed** [comment]
This was a bug introduced today, https://github.com/qmk/qmk_firmware/pull/11581 will fix it.
