### ISSUE TITLE
[Bug] Pinky4 visual layout is not in the shape of the actual keyboard

### ISSUE THREAD

**Issue by Soundtoxin** [qmk/qmk_configurator#874]
## Describe the Bug
All the keys for the Pinky4 show up squished together and left-aligned. It makes it difficult to tell where the halves change over, especially with the thumb keys.

**Comment by yanfali** [comment]
This is because it's missing an info.json. It's not an actual bug  in configurator, just some incomplete metadata on the firmware side. Thanks for reporting. @noroadsleft maybe you can look at it and open an issue on the firmware side.

**Comment by noroadsleft** [comment]
*tfw you find a commit that fixes the reported issue, and the commit is dated July of 2019.* :eyes:
