### ISSUE TITLE
Split keyboard slave gives no Input [Bug] 

### ISSUE THREAD

**Issue by flaschen** [qmk/qmk_configurator#876]
First time poster here, sorry for any inconvenience. 
So I've successfully flashed new firmwares on this keyboard (Redox) before. But as of now the newly compiled hex files somehow fail to let the slave part give input.

Exceptions: 

- when I pull the data cable at the slave, sometimes the last typed characters suddenly appear
- when an older hex file (like from April 2020, created with QMK Configurator) from my archive is flashed, it works flawlessly (but if I compile a new hex file on basis of the then-used json file, the slave doesn't work)

what I tried:

- double and triple checking the settings of QMK Configurator and Toolbox
- rebooting of course
- cleaning the jacks
- using one of the default layouts of QMK Configurator
- comparing the logs of QMK Toolbox (working vs non-working hex file)

It just has to be a bug.

**Comment by yanfali** [comment]
Did you flash both halves? You can't update just one side if it's been a long time between flashing.

**Comment by flaschen** [comment]
Wow, thank you! I'd never have thought of this.
