### ISSUE TITLE
Add support for layout aliases

### ISSUE THREAD

**Issue by skullydazed** [qmk/qmk_configurator#895]
There is a new field in the keyboard JSON- `layout_aliases`. This is a mapping of `alias` -> `LAYOUT_macro`. For example you can find this in the [`clueboard/66/rev3`](http://api.qmk.fm/v1/keyboards/clueboard/66/rev3) JSON:

```
"layout_aliases": {
    "KEYMAP":"LAYOUT_all",
    "LAYOUT":"LAYOUT_all"
}
```

Configurator should use this information at keymap import time to select the correct LAYOUT.

**Comment by yanfali** [comment]
Side convo. Configurator default keymap JSON files contains both a keymap and layout key. As the info.json files evolve and layouts and keymaps get renamed, legacy configurator json files can be left behind and made non-functional by normal maintenance and evolution. Using this new data structure, remappings can be done automatically by the UI so the legacy files continue to work when users attempt to use the old layouts.
