### ISSUE TITLE
gh-pages setup for noobs

### ISSUE THREAD

**Issue by mechmerlin** [qmk/qmk_configurator#90]
We should create documentation on how to do this, in a manner friendly to noobs, such as myself. =). 

1. fork the project
2. git co gh-pages
3. rm CNAME
4. add you _config.yml
5. push to gh-pages
6. reload after about 10-15 seconds

**Comment by yanfali** [comment]
Actually the better way to do this may be through installing jekyll and working locally.

**Comment by yanfali** [comment]
@mechmerlin you should check out the documentation at https://github.com/qmk/qmk_configurator/blob/master/assets/js/development.md to see if this helps.

**Comment by mechmerlin** [comment]
Some work was done on this via PR #140

**Comment by yanfali** [comment]
@mechmerlin this should be resolved now. Thanks!

**Comment by yanfali** [comment]
closing.
