### ISSUE TITLE
BFO 9000 board layout garbled [Bug] 

### ISSUE THREAD

**Issue by admiralmcsassy** [qmk/qmk_configurator#900]
## BFO 9000 board layout garbled

When attempting to configure the bfo9000, the board icons in the json section are all garbled together.
![Screenshot_2021-03-09 QMK Configurator](https://user-images.githubusercontent.com/60167091/110511697-7c30ea00-80d2-11eb-925e-2866a9b391a2.png)

**Comment by nooges** [comment]
Since, BFO-9000 folder was missing an info.json file, it looks like key just gets shoved into a single row. This PR should fix that issue: https://github.com/qmk/qmk_firmware/pull/12179

**Comment by yanfali** [comment]
configurator is metadata driven, so if there isn't a file in qmk_firmware, the UI does the best it can. Glad this is getting resolved.

**Comment by noroadsleft** [comment]
This is fixed.

https://config.qmk.fm/#/keebio/bfo9000/LAYOUT

![image](https://user-images.githubusercontent.com/18669334/110521035-1dfd0a80-80c4-11eb-8423-a53671fe42de.png)
