### ISSUE TITLE
[Bug] Ergodash UI broken

### ISSUE THREAD

**Issue by freeo** [qmk/qmk_configurator#902]
## Describe the Bug

The Ergodash UI layout isn't working as of recently, which makes the configurator completely unusable for this keyboard. See the screenshot. It was fine ~1.5 months ago.
Tested on:
Mac: Chrome
Linux: Chrome,Firefox

Same result everywhere.

## Additional Context

![Screenshot from 2021-03-17 11-39-49](https://user-images.githubusercontent.com/3410566/111455587-4618e900-8716-11eb-9e31-1058037eed1e.png)

**Comment by yanfali** [comment]
It's missing an info.json on the qmk_firmware side, so the UI can't figure out how to render it. Someone needs to add a valid one.

**Comment by yanfali** [comment]
Looks like someone removed the LAYOUT that's default for this keyboard, so it's no longer valid. The API does it's best.

**Comment by yanfali** [comment]
Ah ok. This is related to LAYOUT aliasing issue #895 I guess we need to add this soon.

**Comment by noroadsleft** [comment]
Can confirm this is fixed:

![image](https://user-images.githubusercontent.com/18669334/112084175-9395bb80-8b45-11eb-8cd1-3771ab772e7b.png)
