### ISSUE TITLE
[Bug] Ortho75 is not being displayed correctly

### ISSUE THREAD

**Issue by CGMossa** [qmk/qmk_configurator#907]
I think the layout of ortho75 has too many buttons.

![image](https://user-images.githubusercontent.com/1063624/114570639-4a351980-9c76-11eb-9e62-7a0667eb947d.png)

Can someone see if this can be fixed easily?

See this particular layout [here](https://config.qmk.fm/#/cannonkeys/ortho75/LAYOUT_ortho_5x15).

**Comment by yanfali** [comment]
This isn't a configurator bug per-se. The info.json in QMK configurator is missing a 5x15 layout.

**Comment by yanfali** [comment]
@noroadsleft @awkannan someone needs to update info.json or just use via.

**Comment by noroadsleft** [comment]
This is fixed.

![image](https://user-images.githubusercontent.com/18669334/114670146-8d63ac80-9cb7-11eb-9eda-05a544aa6e86.png)

**Comment by CGMossa** [comment]
Thanks! This was very nice of you all!
