### ISSUE TITLE
Tooltips for Controls

### ISSUE THREAD

**Issue by mechmerlin** [qmk/qmk_configurator#91]
People are getting confused with the controls, especially the import/export button, thinking it is for hex files. We need to add tooltips to our controls briefly describing what they do and what they are for.

**Comment by yanfali** [comment]
maybe Import JSON and Export JSON? Just like Download Hex?

**Comment by mechmerlin** [comment]
I'll take this one, sounds within my skill level

**Comment by yanfali** [comment]
sorry, I already did it

**Comment by yanfali** [comment]
I'll hold off. You do it and add the accept bit from my branch
https://github.com/yanfali/qmk_configurator/commit/859e94e28c780bd16210f8aca342aca46cf6b88b

**Comment by yanfali** [comment]
The accept attribute prevents people from loading file types that aren't JSON.

**Comment by yanfali** [comment]
OK, we discussed this a bit on discord and the general consensus for now is to add the accept attribute to block hex files being loaded, and to use #92 to prevent people import JSON files that are from kbfirmware.

Longer term, QMK needs to register a mime type with IANA and then being using it consistently across the configurator/toolbox.

**Comment by yanfali** [comment]
fixed.
