### ISSUE TITLE
[Bug]  disconnection when trying to download firmware

### ISSUE THREAD

**Issue by Vandeia** [qmk/qmk_configurator#940]
After compiling for an XD75re I hit download firmware where it then attempted to close the page. Were I to click yes it would ask me again then immediately "Secure connection failed" screen with a  PR_CONNECT_RESET_ERROR while trying to take me to nyc3.digitaloceanspaces.com

**Comment by skullydazed** [comment]
Do you consistently get this, or did it only happen one time?

**Comment by noroadsleft** [comment]
Attempted this in Firefox 89.0.1 and had no issues.

**Comment by yanfali** [comment]
I'm going to close  this one as a transient DO issue.
