### ISSUE TITLE
[Bug] Print layout is too wide for larger keyboards

### ISSUE THREAD

**Issue by yanfali** [qmk/qmk_configurator#950]
### Describe the Bug

Easier to demonstrate using an upload

[QMK Configurator.pdf](https://github.com/qmk/qmk_configurator/files/6795739/QMK.Configurator.pdf)

This probably needs the print stylesheet to be adjusted, or tweak the rendering algorithm to fit the page, or perhaps have a setting that try's to scale the print out to fit the page.

### Additional Context?

![Screen Shot 2021-07-10 at 11 08 59 AM](https://user-images.githubusercontent.com/2275667/125172561-40d12580-e16f-11eb-84d8-ceb2d7ea349e.png)

Right most column is cut off

**Comment by noroadsleft** [comment]
Still happens for me on Firefox 94.

[QMK Configurator - fx94.pdf](https://github.com/qmk/qmk_configurator/files/7508437/QMK.Configurator.-.fx94.pdf)
