### ISSUE TITLE
[Bug] Some keyboard layouts bug to just a single line

### ISSUE THREAD

**Issue by AMoonRabbit** [qmk/qmk_configurator#954]
### Describe the Bug

When selecting some of the templates available for a keyboard, the keys all move to just a single line

This has only been found with the coseyfannitutti/discipline keyboard layouts, specifically when selecting LAYOUT_65_ISO, note that if the ISO block version is selected, it loads fine.

![image](https://user-images.githubusercontent.com/3766988/125701663-74ee2695-1467-4b5c-8909-039e7127faca.png)

Tested in Chrome, and Firefox, as well as Internet Explorer

### Additional Context?

[Discipline keyboard layout](https://config.qmk.fm/#/coseyfannitutti/discipline/LAYOUT_65_ISO)

**Comment by AMoonRabbit** [comment]
Could be the same issue as #902?

**Comment by yanfali** [comment]
> Could be the same issue as #902?

Yes. There is no LAYOUT_65_iso layout defined in the layouts in info.json. It's being inferred by the header files.

**Comment by yanfali** [comment]
@noroadsleft this is really a QMK firmware bug I believe.

**Comment by noroadsleft** [comment]
> @noroadsleft this is really a QMK firmware bug I believe.

Yeah, this has to be fixed on `qmk_firmware`. Configurator's looking for data that doesn't exist.

I can sort this.

**Comment by noroadsleft** [comment]
This is fixed for the Discipline. Any layout you select for it should be fully functional.

If you spot any bugs similar to this for any other boards in the future, posting an issue is greatly helpful. I don't have a good method for checking for these sorts of issues at the moment.

Thanks for reporting!

**Comment by AMoonRabbit** [comment]
Thank you for fixing this
