### ISSUE TITLE
"xbows_knight_default.json" needs to be updated

### ISSUE THREAD

**Issue by XBowsTech** [qmk/qmk_configurator#960]
### Information

- [X] None of the other issue templates apply

### Description

The old Keymap is wrong and needs to be updated.
![1](https://user-images.githubusercontent.com/41098278/127424115-9cf6374d-b08a-450a-b519-32b1107f092a.png)

**Comment by noroadsleft** [comment]
This is on my to-do list.

**Comment by XBowsTech** [comment]
> This is on my to-do list.

Thanks！
