### ISSUE TITLE
QMK Configurator Outage (2021-08-08)

### ISSUE THREAD

**Issue by ryanaungs** [qmk/qmk_configurator#967]
### Describe the Bug

When loading https://config.qmk.fm/#/ there is no option to let me select my keyboard. Not sure if this is a bug, or I am doing something wrong. 
- I do not have the QMK keyboard plugged into my MAC. Is this a prerequisite to selecting the keyboard? 
- I have installed toolbox on my MAC.
Here is a screenshot of what I see.
![Screen Shot 2021-08-09 at 1 14 41 AM](https://user-images.githubusercontent.com/88652790/128677073-ae721dd8-bb60-4eb3-843a-bd733d73c01b.png)

Any ideas?

**Comment by noroadsleft** [comment]
Known issue. The task that provides the list of keyboards to QMK Configurator crashed during an update Sunday evening, and it wasn't discovered until after any of the people who are able to fix it signed off for the night.

I imagine this will be fixed sometime early Monday (US Pacific Time, UTC -0700).

**Comment by skullydazed** [comment]
The problem has been fixed by https://github.com/qmk/qmk_firmware/pull/13930.

**Comment by xtaran** [comment]
Maybe this issue should be unpinned as it seems solved for about two months now. :-)
