### ISSUE TITLE
[Bug] GMMK Pro lacking the function layer on the online configurator

### ISSUE THREAD

**Issue by andrebrait** [qmk/qmk_configurator#986]
## Describe the Bug

The GMMK Pro is lacking the function layer on the online configurator. I've checked other keyboards that were added recently and they all show up just fine. I couldn't figure out why the GMMK Pro is only showing the keys assigned on the first layer.

I checked a number of information files and whatnot but everything seems to be the same for other keyboards that show up correctly (like the Keychron Q1).

## System Information

 - Keyboard:  GMMK Pro
   - Revision (if applicable):  
 - Operating system: Irrelevant
 - AVR GCC version: Irrelevant

 - ARM GCC version: Irrelevant

 - QMK Firmware version: Irrelevant

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by andrebrait** [comment]
Can you point me to where I can fix it, in this case?

**Comment by fauxpark** [comment]
Configurator keymaps are stored here:
https://github.com/qmk/qmk_configurator/tree/master/public/keymaps

**Comment by yanfali** [comment]
https://github.com/qmk/qmk_configurator/blob/master/public/keymaps/g/gmmk_pro_ansi_default.json
https://github.com/qmk/qmk_configurator/blob/master/public/keymaps/g/gmmk_pro_iso_default.json

**Comment by andrebrait** [comment]
Ah, perfect.

Thanks.

I shall make a PR for those then.

Andre Brait

**Comment by andrebrait** [comment]
Done.
