### ISSUE TITLE
[Bug] QMK Configurator won't compile even default keymap

### ISSUE THREAD

**Issue by lessavyfav** [qmk/qmk_configurator#990]
### Describe the Bug

Hi there! I'm having a hard time getting my (or any) keymap to compile in the web configurator. It worked fine yesterday. Today it fails without a useful error message...

Loaded 6 layers and 360 keycodes. Defined 11 Any key keycodes
* Sending preonic/rev3:tims-pre3 with LAYOUT_ortho_5x12
* Received job_id: c92045ad-27cc-4c93-a8a8-3d191321a029 _(changes each time as expected)_
* Queueing . . . . _(if there is no queue it just goes straight failed with the potato graphic warning "Abort! Abort!")_
* Failed

In my terminal qmk compile commands are working normally with -km default and my .json files

I tried clearing my cache and searching google for answers with no luck.

Hope this is useful, not a noob fail

**Comment by skullydazed** [comment]
I tried to roll out a fix earlier that broke. I've rolled it back for now.
